# Generated by Django 4.2.16 on 2026-01-08 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('weight', models.IntegerField(default=0, help_text='数字越大，排序越靠前', verbose_name='排序权重')),
            ],
            options={
                'verbose_name': '资源分类',
                'verbose_name_plural': '资源分类',
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CloudType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='网盘名称')),
                ('icon_class', models.CharField(blank=True, help_text='前端图标类名，如：baidu-icon、xunlei-icon', max_length=50, verbose_name='图标类名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网盘类型',
                'verbose_name_plural': '网盘类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('description', models.TextField(blank=True, verbose_name='资源描述')),
                ('keywords', models.CharField(help_text='用逗号分隔，如：电影,科幻,2023', max_length=200, verbose_name='关键词')),
                ('resource_url', models.URLField(max_length=500, verbose_name='资源链接')),
                ('extract_code', models.CharField(blank=True, max_length=20, verbose_name='提取码')),
                ('screenshot', models.ImageField(blank=True, upload_to='screenshots/', verbose_name='资源截图')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('copy_count', models.PositiveIntegerField(default=0, verbose_name='复制链接次数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('collect_count', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('report_count', models.PositiveIntegerField(default=0, verbose_name='举报数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='审核通过')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='分类')),
                ('cloud_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cloudtype', verbose_name='网盘类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='举报时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource', verbose_name='被举报资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='举报用户')),
            ],
            options={
                'verbose_name': '举报记录',
                'verbose_name_plural': '举报记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='core_resour_created_b26772_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-view_count'], name='core_resour_view_co_7561e5_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-copy_count'], name='core_resour_copy_co_9bf2db_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-like_count'], name='core_resour_like_co_447a7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'resource')},
        ),
    ]
