# Generated by Django 4.2.16 on 2026-01-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='screenshot',
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_url',
            field=models.CharField(max_length=500, verbose_name='资源链接'),
        ),
        migrations.CreateModel(
            name='ResourceScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource_screenshots/%Y/%m/', verbose_name='截图')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.resource', verbose_name='所属资源')),
            ],
            options={
                'verbose_name': '资源截图',
                'verbose_name_plural': '资源截图',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
