# Generated by Django 4.2.16 on 2026-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_resource_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='screenshots/', verbose_name='资源截图'),
        ),
        migrations.DeleteModel(
            name='ResourceScreenshot',
        ),
    ]
