# Generated by Django 4.2.16 on 2026-01-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apply_status',
            field=models.CharField(choices=[('not_applied', '未申请'), ('pending', '审核中'), ('approved', '已通过'), ('rejected', '被拒绝')], default='not_applied', max_length=20, verbose_name='申请状态'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='review_message',
            field=models.TextField(blank=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
